image: eclipse-temurin:21-jdk

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

build:
  stage: build
  tags:
    - bas2301
    - linux
  script:
    - chmod +x mvnw
    - ./mvnw clean compile test package
  artifacts:
    paths:
      - target/*.jar

sast:
  stage: test
  image: returntocorp/semgrep
  script:
    - semgrep ci --config auto --sarif --output semgrep.sarif
  artifacts:
    reports:
      sast: semgrep.sarif

dependency_check:
  stage: test
  script:
    - ./mvnw org.owasp:dependency-check-maven:check -Dformat=HTML
  artifacts:
    paths:
      - target/dependency-check-report.html